version: '3.8'
services:

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - localnet

  #https://mxulises.medium.com/simple-prometheus-setup-on-docker-compose-f702d5f98579
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localnet
    ports:
      - 9090:9090

volumes:
  cache:
    driver: local

networks:
  localnet:
    driver: bridge
